// 用户相关类型
export interface User {
  id: string;
  username: string;
  email: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface RegisterRequest {
  username: string;
  email: string;
  password: string;
}

export interface AuthResponse {
  user: User;
  token: string;
}

// 任务状态枚举
export enum TaskStatus {
  PENDING = 'pending',
  IN_PROGRESS = 'in_progress',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled'
}

// 任务优先级
export enum TaskPriority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  URGENT = 'urgent'
}

// 时间范围类型
export enum TimeRange {
  DAY = 'day',
  WEEK = 'week',
  MONTH = 'month',
  QUARTER = 'quarter',
  HALF_YEAR = 'half_year',
  YEAR = 'year'
}

// 计划类型
export enum PlanType {
  YEARLY = 'yearly',
  HALF_YEARLY = 'half_yearly',
  QUARTERLY = 'quarterly',
  MONTHLY = 'monthly',
  WEEKLY = 'weekly',
  DAILY = 'daily'
}

// 报告类型
export enum ReportType {
  DAILY_LOG = 'daily_log',
  WEEKLY_REPORT = 'weekly_report',
  MONTHLY_REPORT = 'monthly_report',
  QUARTERLY_REPORT = 'quarterly_report',
  HALF_YEARLY_REPORT = 'half_yearly_report',
  YEARLY_REPORT = 'yearly_report'
}

// 工作分类
export interface Category {
  id: string;
  name: string;
  color: string;
  description?: string;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}

// 标签
export interface Tag {
  id: string;
  name: string;
  color: string;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}

// 任务
export interface Task {
  id: string;
  title: string;
  description?: string;
  status: TaskStatus;
  priority: TaskPriority;
  categoryId?: string;
  category?: Category;
  tags: Tag[];
  planId?: string; // 关联的计划ID
  startDate?: Date;
  endDate?: Date;
  dueDate?: Date;
  estimatedHours?: number;
  actualHours?: number;
  userId: string;
  parentTaskId?: string;
  subtasks?: Task[];
  createdAt: Date;
  updatedAt: Date;
}

// 分层计划
export interface HierarchicalPlan {
  id: string;
  title: string;
  description?: string;
  type: PlanType;
  year: number;
  quarter?: number; // 1-4
  month?: number; // 1-12
  week?: number; // 1-53
  date?: Date; // 具体日期（仅日计划）
  startDate: Date;
  endDate: Date;
  parentPlanId?: string; // 父计划ID，支持WBS结构
  parentPlan?: HierarchicalPlan;
  childPlans?: HierarchicalPlan[]; // 子计划
  tasks: Task[];
  status: TaskStatus;
  progress: number; // 0-100
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}

// 工作日志
export interface WorkLog {
  id: string;
  date: Date;
  dailyPlanId?: string; // 关联的日计划
  dailyPlan?: HierarchicalPlan;
  plannedTasks: WorkLogTask[]; // 计划内任务
  unplannedTasks: WorkLogTask[]; // 计划外任务
  summary: string; // 日志总结
  reflection?: string; // 反思
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}

// 工作日志任务
export interface WorkLogTask {
  id: string;
  taskId?: string; // 关联的任务ID
  task?: Task;
  title: string;
  description?: string;
  status: TaskStatus;
  timeSpent: number; // 花费时间（分钟）
  isPlanned: boolean; // 是否为计划内任务
  workLogId: string;
}

// 报告
export interface Report {
  id: string;
  title: string;
  type: ReportType;
  period: string; // 报告周期描述，如"2024年第1季度"
  year: number;
  quarter?: number;
  month?: number;
  week?: number;
  startDate: Date;
  endDate: Date;
  content: string; // 报告内容（Markdown格式）
  autoGenerated: boolean; // 是否自动生成
  isEdited: boolean; // 是否被用户编辑过
  sourceReportIds?: string[]; // 源报告ID（用于汇总）
  sourceWorkLogIds?: string[]; // 源工作日志ID（用于周报）
  statistics: ReportStatistics;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}

// 报告统计
export interface ReportStatistics {
  totalTasks: number;
  completedTasks: number;
  totalTimeSpent: number; // 总时间（分钟）
  plannedTasksCount: number;
  unplannedTasksCount: number;
  completionRate: number; // 完成率 0-100
  categoryBreakdown: Array<{
    categoryId: string;
    categoryName: string;
    taskCount: number;
    timeSpent: number;
  }>;
}

// 计划（保留原有接口以兼容现有代码）
export interface Plan {
  id: string;
  title: string;
  description?: string;
  timeRange: TimeRange;
  startDate: Date;
  endDate: Date;
  tasks: Task[];
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}

// 时间记录
export interface TimeLog {
  id: string;
  title?: string; // 时间记录标题
  taskId: string;
  task?: Task;
  taskName?: string; // 任务名称
  category?: string; // 分类
  startTime: Date;
  endTime?: Date;
  duration?: number; // 秒
  description?: string;
  isRunning?: boolean; // 是否正在运行
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}

// 提醒设置
export interface Reminder {
  id: string;
  title: string;
  description: string;
  type: 'task' | 'plan' | 'meeting' | 'deadline' | 'break' | 'custom';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  triggerTime: Date;
  isRecurring: boolean;
  recurringPattern?: {
    type: 'daily' | 'weekly' | 'monthly' | 'yearly';
    interval: number; // 每隔多少个周期
    daysOfWeek?: number[]; // 周几 (0-6, 0为周日)
    dayOfMonth?: number; // 每月第几天
    endDate?: Date;
  };
  isActive: boolean;
  isCompleted: boolean;
  completedAt?: Date;
  snoozeUntil?: Date;
  notificationMethods: ('browser' | 'sound' | 'email')[];
  relatedTaskId?: string;
  relatedPlanId?: string;
  tags: string[];
  createdAt: Date;
  updatedAt: Date;
}

// 模板
export interface Template {
  id: string;
  name: string;
  type: 'task' | 'plan';
  content: any; // JSON格式的模板内容
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}

// 统计数据
export interface Statistics {
  totalTasks: number;
  completedTasks: number;
  totalHours: number;
  categoryStats: Array<{
    category: Category;
    taskCount: number;
    totalHours: number;
  }>;
  timeRangeStats: Array<{
    date: string;
    taskCount: number;
    completedCount: number;
    totalHours: number;
  }>;
}

// API响应类型
export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  message?: string;
  error?: string;
}

// 分页参数
export interface PaginationParams {
  page: number;
  limit: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

// 分页响应
export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

// 筛选参数
export interface TaskFilters {
  status?: TaskStatus[];
  priority?: TaskPriority[];
  categoryId?: string[];
  tagIds?: string[];
  startDate?: Date;
  endDate?: Date;
  search?: string;
}